const KEY='cronograma-estudos-v1';
const navItems=[['inicio','🏠','Início'],['mapeamento','📋','Mapeamento'],['materias','📚','Minhas Matérias'],['cronograma','📅','Cronograma'],['revisoes','🔄','Revisões'],['guia','📖','Guia Científico']];
const activityMeta={Sono:['sleep','💤'],Refeição:['meal','🍳'],'Desloc.':['travel','🚗'],Trabalho:['work','💼'],Estudo:['study','📚'],Revisão:['review','🔄'],Exercício:['exercise','🏋️'],Família:['family','👨‍👩‍👧'],Pausa:['break','⏸️'],Descanso:['rest','😴']};
const times=Array.from({length:36},(_,i)=>{const m=330+i*30;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`});
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];
const sampleSubjects=[['Matemática',1,5,1.5,'Álgebra, Geometria, Estatística'],['Português',1,5,1.5,'Gramática, Interpretação, Redação'],['Biologia',2,4,1,'Citologia, Genética, Ecologia'],['Física',2,4,1,'Mecânica, Termodinâmica'],['Química',2,3,1,'Orgânica, Inorgânica'],['História',3,3,.5,''],['Geografia',3,3,.5,''],['Inglês',2,3,.5,'']];
function baseSchedule(){return days.map((_,d)=>times.map(t=>{const mins=+t.slice(0,2)*60 + +t.slice(3);if(t==='05:30')return'Sono';if(t==='06:00'||t==='12:00'||t==='12:30'||t==='18:30')return'Refeição';if(d<5&&t==='06:30')return'Desloc.';if(d<5&&t==='07:00')return'Exercício';if(d<5&&mins>=450&&mins<=990)return'Trabalho';if(d<5&&(t==='17:00'||t==='17:30'))return'Desloc.';if(d<5&&t==='18:00')return'Pausa';if(d<5&&mins>=1140&&mins<=1260)return'Estudo';if(d<5&&(t==='21:30'||t==='22:00'))return'Família';if(d>=5&&mins>=390&&mins<=450)return'Sono';if(d>=5&&mins>=480&&mins<=570)return t==='08:00'?'Refeição':'Exercício';if(d>=5&&mins>=600&&mins<=930)return'Estudo';if(d>=5&&mins>=960&&mins<=1050)return'Família';if(d>=5&&mins>=1140&&mins<=1230)return'Descanso';if(mins>=1260)return'Sono';return''}))}
function defaultState(){return{mapping:{sleep:'23:00',wake:'07:00',travelOut:60,travelBack:60,workHours:6,workDays:5,familyDaily:3,fixedWeekly:4,exerciseDays:4,exerciseDuration:1.5,mealsDaily:3,hygieneDaily:2,bufferDaily:1},subjects:Array.from({length:20},(_,i)=>{const x=sampleSubjects[i];return x?{name:x[0],priority:x[1],days:x[2],hours:x[3],notes:x[4]}:{name:'',priority:'',days:'',hours:'',notes:''}}),schedule:baseSchedule(),reviews:[{content:'Fotossíntese',subject:'Biologia',date:'2025-06-01',checks:[false,false,false],notes:''},{content:'Equações 2º grau',subject:'Matemática',date:'2025-06-02',checks:[false,false,false],notes:''},{content:'Revolução Industrial',subject:'História',date:'2025-06-03',checks:[false,false,false],notes:''},{content:'Lei de Ohm',subject:'Física',date:'2025-06-04',checks:[false,false,false],notes:''},{content:'Concordância Verbal',subject:'Português',date:'2025-06-05',checks:[false,false,false],notes:''}]}};
let state=load(),page='inicio',toastTimer;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.mapping?x:defaultState()}catch{return defaultState()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));const e=document.querySelector('#saveState');if(e){e.textContent='✓ Salvo';e.style.opacity=1}showToast('Alterações salvas')}
function showToast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1400)}
function n(v){return Number(v)||0}function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function timeHours(a,b){if(!a||!b)return 0;let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number),v=(bh+bm/60)-(ah+am/60);return v>0?v:v+24}
function metrics(){const m=state.mapping,sleep=timeHours(m.sleep,m.wake),travel=(n(m.travelOut)+n(m.travelBack))/60*5,work=n(m.workHours)*n(m.workDays),family=n(m.familyDaily)*7+n(m.fixedWeekly),exercise=n(m.exerciseDays)*n(m.exerciseDuration),routine=(n(m.mealsDaily)+n(m.hygieneDaily))*7,buffer=n(m.bufferDaily)*7,awake=24-sleep,committed=n(m.workHours)+(n(m.travelOut)+n(m.travelBack))/60+n(m.familyDaily)+exercise/7+n(m.mealsDaily)+n(m.hygieneDaily)+n(m.bufferDaily),daily=awake-committed;return{sleep,travel,work,family,exercise,routine,buffer,awake,committed,daily,weekly:daily*7}}
function subjectTotal(s){return n(s.days)*n(s.hours)}function planned(){return state.subjects.reduce((a,s)=>a+subjectTotal(s),0)}
const titles={inicio:['Cronograma de Estudos','Ciência da aprendizagem aplicada à sua rotina.'],mapeamento:['Mapeamento da sua semana real','Preencha os campos azuis; os resultados são calculados automaticamente.'],materias:['Minhas matérias de estudo','Defina prioridades e distribua suas horas disponíveis.'],cronograma:['Cronograma semanal','Clique em qualquer bloco para alternar a atividade.'],revisoes:['Rastreador de revisões','Repetição espaçada automática em 1, 7 e 30 dias.'],guia:['Guia científico','Por que cada decisão do cronograma importa.']};
function init(){document.querySelector('#nav').innerHTML=navItems.map(([id,ic,label])=>`<button class="nav-btn" data-page="${id}">${ic} &nbsp;${label}</button>`).join('');document.querySelector('#nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)};document.querySelector('#menuBtn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#exportBtn').onclick=exportData;document.querySelector('#importInput').onchange=importData;document.querySelector('#resetBtn').onclick=()=>{if(confirm('Restaurar todos os dados de exemplo?')){state=defaultState();save();render()}};go(location.hash.slice(1)||'inicio');window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'inicio',false))}
function go(p,hash=true){if(!titles[p])p='inicio';page=p;if(hash)history.replaceState(null,'','#'+p);document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelector('#pageTitle').textContent=titles[p][0];document.querySelector('#pageSubtitle').textContent=titles[p][1];document.querySelector('#sidebar').classList.remove('open');render();scrollTo(0,0)}
function render(){const f={inicio:home,mapeamento:mapping,materias:subjects,cronograma:schedule,revisoes:reviews,guia:guide}[page];document.querySelector('#content').innerHTML=f();bind()}
function home(){const m=metrics();return `<section class="hero"><h2>Seu plano de estudos, em um só lugar.</h2><p>Organize a rotina real, distribua matérias com honestidade e mantenha as revisões em dia. Tudo é salvo automaticamente neste navegador.</p></section><div class="stats"><div class="stat blue"><span>Horas disponíveis/semana</span><strong>${m.weekly.toFixed(1)}h</strong></div><div class="stat green"><span>Horas planejadas</span><strong>${planned().toFixed(1)}h</strong></div><div class="stat orange"><span>Matérias ativas</span><strong>${state.subjects.filter(s=>s.name).length}</strong></div><div class="stat red"><span>Revisões pendentes</span><strong>${state.reviews.reduce((a,r)=>a+r.checks.filter(x=>!x).length,0)}</strong></div></div><div class="steps">${navItems.slice(1).map(([id,ic,l],i)=>`<div class="step" data-goto="${id}"><span class="step-num">${i+1}</span><strong>${ic} ${l}</strong><p>${titles[id][1]}</p><span>→</span></div>`).join('')}</div>`}
const fields={sleep:['Hora que você vai dormir','time','hh:mm','Anote o horário real, não o ideal'],wake:['Hora que você acorda','time','hh:mm','Use o horário dos dias de semana'],travelOut:['Deslocamento diário IDA','number','min','Inclua trânsito, espera e caminhada'],travelBack:['Deslocamento diário VOLTA','number','min',''],workHours:['Horas de trabalho/escola por dia','number','h/dia','Inclua a pausa do almoço'],workDays:['Dias por semana','number','dias',''],familyDaily:['Tempo com família por dia','number','h/dia','Inclua com honestidade para sustentar o plano'],fixedWeekly:['Compromissos fixos semanais','number','h/sem',''],exerciseDays:['Dias de exercício por semana','number','x/sem','Exercício favorece memória e atenção'],exerciseDuration:['Duração média por sessão','number','h',''],mealsDaily:['Tempo com refeições por dia','number','h/dia','Inclua preparo quando aplicável'],hygieneDaily:['Tempo de higiene, banho e rotina','number','h/dia',''],bufferDaily:['Buffer diário para imprevistos','number','h/dia','Mínimo recomendado: 0,5h']};
function field(k){const f=fields[k];return `<div>${f[0]}</div><div><input data-map="${k}" type="${f[1]}" step="${f[1]==='number'?'0.5':''}" value="${esc(state.mapping[k])}"></div><div class="unit">${f[2]}</div><div class="tip">${f[3]}</div>`}
function calcRow(label,val,unit){return `<div>${label}</div><div class="calculated">${val}</div><div class="unit">${unit}</div><div></div>`}
function panel(cls,title,body){return `<section class="panel ${cls}"><div class="panel-head">${title}</div><div class="panel-body"><div class="form-grid">${body}</div></div></section>`}
function mapping(){const x=metrics();return `${panel('purple','🌙 SONO',field('sleep')+field('wake')+calcRow('Horas de sono por noite',x.sleep.toFixed(1),'h/noite')+calcRow('Horas de sono por semana',(x.sleep*7).toFixed(1),'h/sem'))}${panel('blue','🚗 DESLOCAMENTO',field('travelOut')+field('travelBack')+calcRow('Total de deslocamento por semana',x.travel.toFixed(1),'h/sem'))}${panel('blue','💼 ESCOLA / TRABALHO',field('workHours')+field('workDays')+calcRow('Total de trabalho por semana',x.work.toFixed(1),'h/sem'))}${panel('purple','👨‍👩‍👧 FAMÍLIA',field('familyDaily')+field('fixedWeekly')+calcRow('Total semanal família + compromissos',x.family.toFixed(1),'h/sem'))}${panel('teal','🏋️ EXERCÍCIO FÍSICO',field('exerciseDays')+field('exerciseDuration')+calcRow('Total de exercício por semana',x.exercise.toFixed(1),'h/sem'))}${panel('orange','🍽️ REFEIÇÕES E ROTINA PESSOAL',field('mealsDaily')+field('hygieneDaily')+calcRow('Total de rotina por semana',x.routine.toFixed(1),'h/sem'))}${panel('gray','🔧 BUFFER E IMPREVISTOS',field('bufferDaily')+calcRow('Total de buffer por semana',x.buffer.toFixed(1),'h/sem'))}<section class="summary"><h3>📊 RESUMO AUTOMÁTICO — HORAS DISPONÍVEIS</h3><div class="summary-row"><strong>${x.awake.toFixed(1)}</strong><span>Horas acordado por dia</span><small>h/dia</small></div><div class="summary-row warn"><strong>${x.committed.toFixed(1)}</strong><span>Horas comprometidas por dia</span><small>h/dia</small></div><div class="summary-row"><strong>${x.daily.toFixed(1)}</strong><span>HORAS DISPONÍVEIS PARA ESTUDO POR DIA</span><small>h/dia</small></div><div class="summary-row"><strong>${x.weekly.toFixed(1)}</strong><span>HORAS DISPONÍVEIS PARA ESTUDO POR SEMANA</span><small>h/sem</small></div></section>`}
function subjects(){const total=planned(),avail=metrics().weekly,diff=total-avail;return `<div class="table-wrap"><table><thead><tr><th>#</th><th>MATÉRIA</th><th>PRIORIDADE<br>(1=Alta)</th><th>DIAS/SEM</th><th>H/DIA</th><th>H/SEM<br>(auto)</th><th>% TEMPO<br>(auto)</th><th>OBSERVAÇÕES</th></tr></thead><tbody>${state.subjects.map((s,i)=>`<tr><td>${i+1}</td><td class="text"><input data-sub="${i}:name" value="${esc(s.name)}"></td><td><select class="priority" data-sub="${i}:priority"><option value=""></option>${[1,2,3].map(v=>`<option ${String(s.priority)===String(v)?'selected':''}>${v}</option>`).join('')}</select></td><td><input type="number" min="0" max="7" step="1" data-sub="${i}:days" value="${esc(s.days)}"></td><td><input type="number" min="0" step="0.5" data-sub="${i}:hours" value="${esc(s.hours)}"></td><td class="auto">${s.name?subjectTotal(s).toFixed(1):''}</td><td class="auto">${s.name&&total?Math.round(subjectTotal(s)/total*100)+'%':''}</td><td class="text"><input data-sub="${i}:notes" value="${esc(s.notes)}"></td></tr>`).join('')}</tbody><tfoot><tr><td colspan="5">TOTAIS</td><td>${total.toFixed(1)}h</td><td>${total?'100%':'0%'}</td><td>horas semanais planejadas</td></tr></tfoot></table></div><div class="notice ${diff>0?'warning':'success'}">${diff>0?`⚠️ Planejou <strong>${diff.toFixed(1)}h a mais</strong> do que tem disponível. Reduza dias/semana ou h/dia.`:`✅ Planejamento compatível com suas horas disponíveis (${avail.toFixed(1)}h/sem).`}</div>`}
function slotButton(v,d,i){const [cl,ic]=activityMeta[v]||['',''];return `<button class="slot ${cl}" data-slot="${d}:${i}" title="Clique para alterar">${ic} ${esc(v)}</button>`}
function schedule(){return `<div class="stats"><div class="stat blue"><span>Horas disponíveis</span><strong>${metrics().weekly.toFixed(1)}h</strong></div><div class="stat green"><span>Total planejado</span><strong>${planned().toFixed(1)}h</strong></div><div class="stat orange"><span>Blocos de estudo</span><strong>${state.schedule.flat().filter(x=>x==='Estudo').length}</strong></div><div class="stat red"><span>Duração do bloco</span><strong>30min</strong></div></div><div class="subjects-chips">${state.subjects.filter(s=>s.name).map(s=>`<span class="chip">${esc(s.name)} · ${subjectTotal(s).toFixed(1)}h</span>`).join('')}</div><div class="schedule-wrap"><table class="schedule"><thead><tr><th>HORÁRIO</th>${days.map(d=>`<th>${d.toUpperCase()}</th>`).join('')}</tr></thead><tbody>${times.map((t,i)=>`<tr><td>${t}</td>${days.map((_,d)=>`<td>${slotButton(state.schedule[d][i]||'',d,i)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="legend">${Object.entries(activityMeta).map(([x,[c,ic]])=>`<button class="${c}">${ic} ${x}</button>`).join('')}</div>`}
function addDays(s,k){if(!s)return'';const d=new Date(s+'T12:00:00');if(Number.isNaN(d.getTime()))return'';d.setDate(d.getDate()+k);return d.toLocaleDateString('pt-BR')}
function dueClass(s,k,done){if(!s||done)return done?'done':'';const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+k);const now=new Date();now.setHours(0,0,0,0);const delta=(d-now)/864e5;return delta<0?'due':delta<=2?'soon':''}
function reviews(){const rows=Array.from({length:Math.max(40,state.reviews.length+1)},(_,i)=>state.reviews[i]||{content:'',subject:'',date:'',checks:[false,false,false],notes:''});return `<div class="toolbar"><button class="btn" id="addReview">+ Nova revisão</button></div><div class="table-wrap"><table><thead><tr><th>#</th><th>CONTEÚDO ESTUDADO</th><th>MATÉRIA</th><th>DATA ESTUDO</th><th>REV 1<br>+1 dia</th><th>REV 2<br>+7 dias</th><th>REV 3<br>+30 dias</th><th>R1</th><th>R2</th><th>R3</th><th>OBSERVAÇÕES</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td class="text"><input data-rev="${i}:content" value="${esc(r.content)}"></td><td><input class="priority" list="subjects" data-rev="${i}:subject" value="${esc(r.subject)}"></td><td><input type="date" data-rev="${i}:date" value="${esc(r.date)}"></td>${[1,7,30].map((k,j)=>`<td class="auto ${dueClass(r.date,k,r.checks[j])}">${addDays(r.date,k)}</td>`).join('')}${[0,1,2].map(j=>`<td><input type="checkbox" data-check="${i}:${j}" ${r.checks[j]?'checked':''}></td>`).join('')}<td class="text"><input data-rev="${i}:notes" value="${esc(r.notes)}"></td></tr>`).join('')}</tbody></table></div><datalist id="subjects">${state.subjects.filter(s=>s.name).map(s=>`<option value="${esc(s.name)}">`).join('')}</datalist><div class="notice warning">🔴 Vermelho: vencida &nbsp; · &nbsp; 🟡 Amarelo: vence em até 2 dias &nbsp; · &nbsp; Marque R1, R2 e R3 ao concluir.</div>`}
const guides=[['purple','🌙 SONO — Não é opcional','Durante o sono (ondas lentas + REM), o hipocampo transfere memórias recentes ao córtex, tornando-as permanentes. Uma noite com menos de 6h reduz a capacidade de formar novas memórias.','Walker (2017) · Diekelmann & Born (2010)'],['yellow','⏸️ PAUSAS — Parte do aprendizado','Durante pausas de repouso, o hipocampo reproduz e reorganiza memórias. Evite preencher imediatamente toda pausa com novos estímulos.','Dewar et al. (2012) · Tambini et al. (2010)'],['teal','🏋️ EXERCÍCIO — Protege o cérebro','Atividade aeróbica aumenta BDNF, proteína que promove crescimento de neurônios. Academia não é luxo no cronograma: é estratégia.','Ratey (2008) · Erickson et al. (2011)'],['blue','🧠 PICO COGNITIVO — Aloque o difícil','Cada pessoa tem picos cognitivos ao longo do dia. Coloque conteúdo exigente no seu pico e revisões fora dele.','Folkard & Monk (1985) · Anderson et al. (2014)'],['green','🔄 REPETIÇÃO ESPAÇADA','Revisar em intervalos diminui a curva do esquecimento. Cada revisão reconsolida a memória e afasta a próxima revisão.','Ebbinghaus (1885) · Cepeda et al. (2006)'],['purple','🔀 INTERLEAVING — Misture matérias','Alternar matérias pode produzir mais retenção do que uma sessão inteira de uma única matéria. A dificuldade durante a prática favorece a aprendizagem posterior.','Kornell & Bjork (2008) · Samani & Pan (2021)'],['orange','💪 CONSISTÊNCIA > PERFEIÇÃO','Um dia perdido não justifica abandonar o plano. Revise o cronograma semanalmente, ajuste sem culpa e retome no próximo bloco.','Duckworth (2016) · Baumeister — Self-Control']];
function guide(){return `<div class="guide-grid">${guides.map(g=>`<article class="guide-card ${g[0]}"><h3>${g[1]}</h3><p>${g[2]}</p><cite>📚 ${g[3]}</cite></article>`).join('')}</div>`}
function ensureReview(i){while(state.reviews.length<=i)state.reviews.push({content:'',subject:'',date:'',checks:[false,false,false],notes:''})}
function bind(){document.querySelectorAll('[data-goto]').forEach(x=>x.onclick=()=>go(x.dataset.goto));document.querySelectorAll('[data-map]').forEach(x=>x.onchange=e=>{state.mapping[e.target.dataset.map]=e.target.type==='number'?n(e.target.value):e.target.value;save();render()});document.querySelectorAll('[data-sub]').forEach(x=>x.onchange=e=>{const[i,k]=e.target.dataset.sub.split(':');state.subjects[i][k]=['priority','days','hours'].includes(k)?(e.target.value===''?'':n(e.target.value)):e.target.value;save();render()});document.querySelectorAll('[data-slot]').forEach(x=>x.onclick=e=>{const[d,i]=e.currentTarget.dataset.slot.split(':').map(Number),keys=['','Sono','Refeição','Desloc.','Trabalho','Estudo','Revisão','Exercício','Família','Pausa','Descanso'],cur=state.schedule[d][i],next=keys[(keys.indexOf(cur)+1)%keys.length];state.schedule[d][i]=next;save();e.currentTarget.parentElement.innerHTML=slotButton(next,d,i);bind()});document.querySelectorAll('[data-rev]').forEach(x=>x.onchange=e=>{const[i,k]=e.target.dataset.rev.split(':');ensureReview(+i);state.reviews[i][k]=e.target.value;save();render()});document.querySelectorAll('[data-check]').forEach(x=>x.onchange=e=>{const[i,j]=e.target.dataset.check.split(':').map(Number);ensureReview(i);state.reviews[i].checks[j]=e.target.checked;save();render()});const add=document.querySelector('#addReview');if(add)add.onclick=()=>{state.reviews.push({content:'',subject:'',date:new Date().toISOString().slice(0,10),checks:[false,false,false],notes:''});save();render()}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cronograma-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Backup exportado')}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.mapping||!x.subjects||!x.schedule)throw 0;state=x;save();render();showToast('Backup importado')}catch{alert('Arquivo de backup inválido.')}};r.readAsText(f);e.target.value=''}
init();
